name: lcastrooliveira.dev
title: lcastrooliveira.dev | Blog sobre Java & friends
description: Blog de desenvolvimento Web com tutoriais de dicas construído por Lucas de Castro Oliveira
tags:
  - blog
  - dev
  - web
  - java
  - devops
email: lcastro.oliveira@gmail.com
disqus_username: lcastrooliveira-dev
show_hero: true
menu:
  - title: Home
    url: /
  - title: Sobre
    url: /about
  - title: Contato
    url: /contact
  - title: Feed
    url: /feed.xml
